# binder environment
name: jupysql-binder

channels:
  - conda-forge

dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - pip
  - pip:
    - jupyterlab_myst # display admonitions in jupyterlab
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    # package
    - -e .
    # required to open .md files as nbs
    - jupytext
